name: dashboard
channels:
  - conda-forge
dependencies:
  - python=3.9
  - sqlalchemy
  - pip
  - pip:
      - streamlit
      - watchdog
      - plotly
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta
      - pyyaml
      - commlib-py
      - jupyter
      - streamlit-elements
      - optuna
      - optuna-dashboard
      - pathlib
      - streamlit-ace
      - st-pages
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
      - git+https://github.com/hummingbot/docker-manager.git
